### ISSUE TITLE
Fix non working pnpm dev

### ISSUE THREAD

**Issue by DrStrangeloovee** [DrStrangeloovee/Elevate360#14]
Currently running `pnpm dev` leads to the following error message:
```shell
error when starting dev server:
file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.80_vite@5.1.6/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:3
import { svelteInspector } from '@sveltejs/vite-plugin-svelte-inspector';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'svelteInspector' not found. The requested module '@sveltejs/vite-plugin-svelte-inspector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltejs/vite-plugin-svelte-inspector';
const { svelteInspector } = pkg;
   at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async load_config (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/@sveltejs+kit@2.5.4_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.80_vite@5.1.6/node_modules/@sveltejs/kit/src/core/config/index.js:70:17)
    at async sveltekit (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/@sveltejs+kit@2.5.4_@sveltejs+vite-plugin-svelte@3.0.2_svelte@5.0.0-next.80_vite@5.1.6/node_modules/@sveltejs/kit/src/exports/vite/index.js:148:24)
    at async Promise.all (index 0)
    at async asyncFlatten (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/vite@5.1.6_sass@1.72.0/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:12997:16)
    at async resolveConfig (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/vite@5.1.6_sass@1.72.0/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:67756:29)
    at async _createServer (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/vite@5.1.6_sass@1.72.0/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:64370:20)
    at async CAC.<anonymous> (file:///C:/Users/nickm/OneDrive%20-%20FH%20Technikum%20Wien/2.%20Semester/ITP/Elevate360/node_modules/.pnpm/vite@5.1.6_sass@1.72.0/node_modules/vite/dist/node/cli.js:762:24)
 ELIFECYCLE  Command failed with exit code 1.
```

It is currently unclear what causes this... I am investigating this right now.

**Comment by DrStrangeloovee** [comment]
Re-created the project setup on [14-fix-non-working-pnpm-dev](https://github.com/DrStrangeloovee/Elevate360/tree/14-fix-non-working-pnpm-dev) for a clean and (hopefully) working dev environment for everyone.
Waiting for feedback from:
- [ ] @NickMuellner 
- [ ] @AhmHagar 
- [ ] @Ramariam 
- [ ] @Itaher10

**Comment by DrStrangeloovee** [comment]
Found cause of @NickMuellner issue with running the dev environment. His local folder was synced to OneDrive and somehow that blocked the dev server from starting.

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bricep, @SealsLuo, @nishimweprince, @factreset, @marciocamurati, @samchaaa, @bookz971, @sunxiaotianmg, @takahiro-prog, @paulrao99, @wiseguytrading, @wesdoniak, @vbm290, @canyuan0801, @euyuil, @TempleOfTemplar, @eihabhala, @tobyb8240, @masking, @tylrha, @devonindustries, @srivatsahg, @cdunca, @tlk3, @HamidBenoum, @JudeVJoseph, @hanryliao, @tsgsz, @Thani-B, @ykpasupulati, @sarahelaina, @Hirschfuchs, @yamstudio, @ctavolazzi, @KyleCK, @DidierRLopes, @Aleksask, @sebastian-diaconescu, @tmcg0, @martinvd, @crusoeworld, @zhuzp98, @ladeng117, @abmyii, @Dirvann, @Fu-Yilei, @saidatta, @tohlh, @0t3ch, @PogoRollo

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
13477940, @fanshuai, @zbioe, @nickwarrior5, @ZhongAlex, @Avantgarde95, @Mlncholy, @RecoFu, @1235saying, @damajor, @vnindex, @BlackSenPig, @realzbc, @sydbarrett74, @huynhdev24, @yanghcc, @SNAILTHELAZY, @xingran521, @petuhovskiy, @LindbergGoes, @neklyud, @HikaruSATO-is-LightningSugar, @michaeliuNO1, @kittokin, @kurt-vonnegut, @HB00, @iedmrc, @bbjansen, @ilCapo01, @Adora233, @zhiwei1998, @kemchos, @codewithgun, @jtianling, @ex-alice, @deepakggoel, @lootnath, @ytaijp, @lertsoft, @vbcc2001, @nineth9t, @MiratPH, @xcorp1986, @implistarry, @louis030195, @SAMUSENPS, @Mrfiregem, @ismartcoding, @reyesvicente, @myiwen

**Comment by andutzu7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Ta180m, @lollyq04, @rivandi852, @ephzero, @Faguiro, @huynhdev24, @HDark15, @cadyrayller, @teathinker, @RuslanBitcash, @fluse, @bossoff, @WreckingE, @amlcodes, @yohayoha, @zhaifg, @AlexWebArchitect, @alvinc21, @Necklaces, @dasibcryptoidology, @youngqqcn, @khaidardotco, @vahidborhani, @slaughtering, @mac-code, @edgardfons, @Kensingtonn, @Lionz01, @GKxR, @AndrusTaylor, @mcthesw, @eldepor, @maksimkristmass, @Teebor-Choka, @johnathan-codes, @kamaladenalhomsi, @catsmells, @kodjosama, @ImpulseHD, @LetsTwist, @GE2Graf19186, @coinsky, @MiniFullC, @BurningBright, @zpengcom, @allanavelar, @koltci, @hasobi, @newrerio, @damianlezcano44
